# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'corridorNode_testJig.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(357, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lsensor_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.lsensor_bar.setProperty("value", 24)
        self.lsensor_bar.setObjectName("lsensor_bar")
        self.verticalLayout.addWidget(self.lsensor_bar)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.msensor_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.msensor_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msensor_bar.setAutoFillBackground(False)
        self.msensor_bar.setProperty("value", 24)
        self.msensor_bar.setTextVisible(False)
        self.msensor_bar.setObjectName("msensor_bar")
        self.verticalLayout.addWidget(self.msensor_bar)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.msensor_label = QtWidgets.QLabel(self.centralwidget)
        self.msensor_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msensor_label.setObjectName("msensor_label")
        self.verticalLayout.addWidget(self.msensor_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.wled_slider = QtWidgets.QSlider(self.centralwidget)
        self.wled_slider.setOrientation(QtCore.Qt.Vertical)
        self.wled_slider.setObjectName("wled_slider")
        self.gridLayout.addWidget(self.wled_slider, 1, 3, 1, 1)
        self.cled_plabel = QtWidgets.QLabel(self.centralwidget)
        self.cled_plabel.setObjectName("cled_plabel")
        self.gridLayout.addWidget(self.cled_plabel, 2, 1, 1, 1)
        self.cled_vlabel = QtWidgets.QLabel(self.centralwidget)
        self.cled_vlabel.setObjectName("cled_vlabel")
        self.gridLayout.addWidget(self.cled_vlabel, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.wled_plabel = QtWidgets.QLabel(self.centralwidget)
        self.wled_plabel.setObjectName("wled_plabel")
        self.gridLayout.addWidget(self.wled_plabel, 2, 3, 1, 1)
        self.cled_slider = QtWidgets.QSlider(self.centralwidget)
        self.cled_slider.setOrientation(QtCore.Qt.Vertical)
        self.cled_slider.setObjectName("cled_slider")
        self.gridLayout.addWidget(self.cled_slider, 1, 1, 1, 1)
        self.wled_vlabel = QtWidgets.QLabel(self.centralwidget)
        self.wled_vlabel.setObjectName("wled_vlabel")
        self.gridLayout.addWidget(self.wled_vlabel, 3, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Corridor Node Test Jig UI"))
        self.label_7.setText(_translate("MainWindow", "Light sensor"))
        self.label_8.setText(_translate("MainWindow", "Motion sensor"))
        self.msensor_label.setText(_translate("MainWindow", "Pulse duration: 0 ms"))
        self.cled_plabel.setText(_translate("MainWindow", "0 %"))
        self.cled_vlabel.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Cold LED"))
        self.label_2.setText(_translate("MainWindow", "Warm LED"))
        self.wled_plabel.setText(_translate("MainWindow", "0 %"))
        self.wled_vlabel.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
