M48
; DRILL file {KiCad 8.0.1} date 2024-06-22T11:42:11+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-22T11:42:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X5.0781Y-4.5833
X5.1181Y-4.3833
X5.1581Y-4.5833
T2
X4.4439Y-5.1969
X5.0837Y-4.252
M30
